const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "923251039272"
const SESSION_ID = "PRABATH-MD~vM8XDQBS#BkrlLRzJnWUHanSgpIPl9tjJ6B2SFhr5bSrzxTPDHj8"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
